# Generated by Django 6.0.1 on 2026-01-27 02:17

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_latitude', models.FloatField(blank=True, null=True)),
                ('birth_longitude', models.FloatField(blank=True, null=True)),
                ('life_path', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('soul_urge', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('expression', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('personality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('sun_sign', models.CharField(max_length=20)),
                ('moon_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('rising_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('chart_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('chart_data', models.JSONField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('photos', models.JSONField(default=list)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20, null=True)),
                ('interested_in', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('age_min_preference', models.IntegerField(default=18)),
                ('age_max_preference', models.IntegerField(default=99)),
                ('distance_km_preference', models.IntegerField(default=100)),
                ('women_first_messaging', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('daily_discover_count', models.IntegerField(default=0)),
                ('daily_discover_reset', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['life_path'], name='users_life_pa_dc433c_idx'), models.Index(fields=['sun_sign'], name='users_sun_sig_4dacb5_idx'), models.Index(fields=['is_active', 'is_profile_complete'], name='users_is_acti_6725d9_idx'), models.Index(fields=['gender'], name='users_gender_c12881_idx')],
            },
        ),
    ]
