# Generated by Django 6.0.1 on 2026-01-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('token', models.TextField()),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('match_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('forecast_notifications', models.BooleanField(default=True)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('os_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'indexes': [models.Index(fields=['user', 'platform'], name='devices_user_id_0e2fa2_idx'), models.Index(fields=['token'], name='devices_token_fa5a84_idx')],
            },
        ),
    ]
