# Generated by Django 6.0.1 on 2026-01-12 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_score', models.SmallIntegerField(help_text='Structure axis score (numerology heavy)')),
                ('dynamics_score', models.SmallIntegerField(help_text='Dynamics axis score (asymmetric/directional)')),
                ('culture_score', models.SmallIntegerField(help_text='Culture axis score (zodiac)')),
                ('affinity_score', models.SmallIntegerField(default=0, help_text='Affinity axis score (auxiliary factors)')),
                ('time_score', models.SmallIntegerField(help_text='Time axis score (cycle alignment)')),
                ('total_score', models.SmallIntegerField(help_text='Total compatibility score (0-100)')),
                ('dominant_axis', models.CharField(help_text='Dominant compatibility axis', max_length=20)),
                ('match_type', models.CharField(help_text='Match type classification', max_length=30)),
                ('risk_level', models.CharField(help_text='Risk level (low/medium/high)', max_length=10)),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('longevity_forecast', models.CharField(max_length=200)),
                ('computation_year', models.SmallIntegerField(help_text='Year this compatibility was computed for')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compatibility_cache',
            },
        ),
        migrations.CreateModel(
            name='Resonance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user1_resonated_at', models.DateTimeField(blank=True, null=True)),
                ('user2_resonated_at', models.DateTimeField(blank=True, null=True)),
                ('eros_activated_at', models.DateTimeField(blank=True, help_text='Timestamp when mutual match was achieved', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mutual', 'Mutual'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compatibility_score', models.SmallIntegerField(help_text='Compatibility score when resonance was created')),
                ('match_type', models.CharField(help_text='Match type when resonance was created', max_length=30)),
            ],
            options={
                'db_table': 'resonances',
            },
        ),
    ]
