# Generated by Django 6.0.1 on 2026-01-12 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compatibilitycache',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compatibilitycache',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resonance',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resonance',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='compatibilitycache',
            index=models.Index(fields=['user1', 'total_score'], name='compatibili_user1_i_3d355c_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitycache',
            index=models.Index(fields=['user2', 'total_score'], name='compatibili_user2_i_4f7dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitycache',
            index=models.Index(fields=['match_type'], name='compatibili_match_t_f5ed76_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitycache',
            index=models.Index(fields=['computation_year'], name='compatibili_computa_5f5e3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilitycache',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['user1', 'status'], name='resonances_user1_i_89b1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['user2', 'status'], name='resonances_user2_i_288818_idx'),
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['status', 'eros_activated_at'], name='resonances_status_de1fad_idx'),
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['created_at'], name='resonances_created_b5923d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resonance',
            unique_together={('user1', 'user2')},
        ),
    ]
