# Generated by Django 6.0.1 on 2026-01-27 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resonance',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_resonances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resonance',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_resonances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'created_at'], name='matches_user1_i_1cb41d_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'created_at'], name='matches_user2_i_de8462_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['from_user', 'action'], name='resonances_from_us_9ceb13_idx'),
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['to_user', 'action'], name='resonances_to_user_302eee_idx'),
        ),
        migrations.AddIndex(
            model_name='resonance',
            index=models.Index(fields=['expires_at'], name='resonances_expires_6d6143_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resonance',
            unique_together={('from_user', 'to_user')},
        ),
    ]
