# Generated by Django 6.0.1 on 2026-01-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('life_path', models.IntegerField(blank=True, null=True)),
                ('soul_urge', models.IntegerField(blank=True, null=True)),
                ('expression', models.IntegerField(blank=True, null=True)),
                ('personality', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'marketing_leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_sent', 'subscribed'], name='marketing_l_email_s_170341_idx'), models.Index(fields=['source', 'created_at'], name='marketing_l_source_07c7dc_idx')],
            },
        ),
    ]
