# Generated by Django 6.0.1 on 2026-01-12 17:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('life_path', models.SmallIntegerField(help_text='Life path number (1-9, 11, 22, 33)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('day_number', models.SmallIntegerField(help_text='Day number (1-9)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('month_number', models.SmallIntegerField(help_text='Month number (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('soul_urge', models.SmallIntegerField(blank=True, help_text='Soul urge number (desire axis)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('expression', models.SmallIntegerField(blank=True, help_text='Expression number (bond axis)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('challenge', models.SmallIntegerField(blank=True, help_text='Challenge number (friction axis)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
                ('zodiac_animal', models.CharField(help_text='Chinese/Turkish zodiac animal', max_length=20)),
                ('zodiac_element', models.CharField(help_text='Zodiac element (water, metal, wood, fire)', max_length=10)),
                ('zodiac_position', models.SmallIntegerField(help_text='Position on zodiac wheel (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('seeking', models.CharField(blank=True, max_length=20, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('use_turkish_letters', models.BooleanField(default=False, help_text='Use Turkish letter mappings for name calculations')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['life_path'], name='users_life_pa_dc433c_idx'), models.Index(fields=['zodiac_animal', 'zodiac_element'], name='users_zodiac__6808e7_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
    ]
